-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 14:18:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema online_store_final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_store_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_store_final` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `online_store_final` ;

-- -----------------------------------------------------
-- Table `online_store_final`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`categories` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `online_store_final`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`users` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `full_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `online_store_final`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`orders` (
  `order_id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_store_final`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `online_store_final`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`products` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(100) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `online_store_final`.`categories` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `online_store_final`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`reviews` (
  `review_id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  `review_text` VARCHAR(100) NULL DEFAULT NULL,
  `review_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `reviews_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_store_final`.`users` (`user_id`),
  CONSTRAINT `reviews_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_store_final`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `online_store_final` ;

-- -----------------------------------------------------
-- Placeholder table for view `online_store_final`.`august23_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`august23_reviews` (`review_id` INT, `user_id` INT, `product_id` INT, `rating` INT, `review_text` INT, `review_date` INT);

-- -----------------------------------------------------
-- Placeholder table for view `online_store_final`.`december23_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`december23_reviews` (`review_id` INT, `user_id` INT, `product_id` INT, `rating` INT, `review_text` INT, `review_date` INT);

-- -----------------------------------------------------
-- Placeholder table for view `online_store_final`.`full_product_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`full_product_info` (`category_id` INT, `category_name` INT, `product_id` INT, `product_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `online_store_final`.`july23_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`july23_reviews` (`review_id` INT, `user_id` INT, `product_id` INT, `rating` INT, `review_text` INT, `review_date` INT);

-- -----------------------------------------------------
-- Placeholder table for view `online_store_final`.`november23_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`november23_reviews` (`review_id` INT, `user_id` INT, `product_id` INT, `rating` INT, `review_text` INT, `review_date` INT);

-- -----------------------------------------------------
-- Placeholder table for view `online_store_final`.`october23_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`october23_reviews` (`review_id` INT, `user_id` INT, `product_id` INT, `rating` INT, `review_text` INT, `review_date` INT);

-- -----------------------------------------------------
-- Placeholder table for view `online_store_final`.`product_avg_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`product_avg_rating` (`product_id` INT, `product_name` INT, `average_rating` INT);

-- -----------------------------------------------------
-- Placeholder table for view `online_store_final`.`reviews_plus_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`reviews_plus_user` (`review_id` INT, `review_date` INT, `reviewer_name` INT, `product_name` INT, `rating` INT, `review_text` INT);

-- -----------------------------------------------------
-- Placeholder table for view `online_store_final`.`september23_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_store_final`.`september23_reviews` (`review_id` INT, `user_id` INT, `product_id` INT, `rating` INT, `review_text` INT, `review_date` INT);

-- -----------------------------------------------------
-- View `online_store_final`.`august23_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_final`.`august23_reviews`;
USE `online_store_final`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `online_store_final`.`august23_reviews` AS select `online_store_final`.`reviews`.`review_id` AS `review_id`,`online_store_final`.`reviews`.`user_id` AS `user_id`,`online_store_final`.`reviews`.`product_id` AS `product_id`,`online_store_final`.`reviews`.`rating` AS `rating`,`online_store_final`.`reviews`.`review_text` AS `review_text`,`online_store_final`.`reviews`.`review_date` AS `review_date` from `online_store_final`.`reviews` where ((`online_store_final`.`reviews`.`review_date` >= '2023-08-01') and (`online_store_final`.`reviews`.`review_date` < '2023-09-01'));

-- -----------------------------------------------------
-- View `online_store_final`.`december23_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_final`.`december23_reviews`;
USE `online_store_final`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `online_store_final`.`december23_reviews` AS select `online_store_final`.`reviews`.`review_id` AS `review_id`,`online_store_final`.`reviews`.`user_id` AS `user_id`,`online_store_final`.`reviews`.`product_id` AS `product_id`,`online_store_final`.`reviews`.`rating` AS `rating`,`online_store_final`.`reviews`.`review_text` AS `review_text`,`online_store_final`.`reviews`.`review_date` AS `review_date` from `online_store_final`.`reviews` where ((`online_store_final`.`reviews`.`review_date` >= '2023-12-01') and (`online_store_final`.`reviews`.`review_date` < '2024-01-01'));

-- -----------------------------------------------------
-- View `online_store_final`.`full_product_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_final`.`full_product_info`;
USE `online_store_final`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `online_store_final`.`full_product_info` AS select `c`.`category_id` AS `category_id`,`c`.`category_name` AS `category_name`,`p`.`product_id` AS `product_id`,`p`.`product_name` AS `product_name` from (`online_store_final`.`categories` `c` join `online_store_final`.`products` `p` on((`c`.`category_id` = `p`.`category_id`)));

-- -----------------------------------------------------
-- View `online_store_final`.`july23_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_final`.`july23_reviews`;
USE `online_store_final`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `online_store_final`.`july23_reviews` AS select `online_store_final`.`reviews`.`review_id` AS `review_id`,`online_store_final`.`reviews`.`user_id` AS `user_id`,`online_store_final`.`reviews`.`product_id` AS `product_id`,`online_store_final`.`reviews`.`rating` AS `rating`,`online_store_final`.`reviews`.`review_text` AS `review_text`,`online_store_final`.`reviews`.`review_date` AS `review_date` from `online_store_final`.`reviews` where ((`online_store_final`.`reviews`.`review_date` >= '2023-07-01') and (`online_store_final`.`reviews`.`review_date` < '2023-08-01'));

-- -----------------------------------------------------
-- View `online_store_final`.`november23_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_final`.`november23_reviews`;
USE `online_store_final`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `online_store_final`.`november23_reviews` AS select `online_store_final`.`reviews`.`review_id` AS `review_id`,`online_store_final`.`reviews`.`user_id` AS `user_id`,`online_store_final`.`reviews`.`product_id` AS `product_id`,`online_store_final`.`reviews`.`rating` AS `rating`,`online_store_final`.`reviews`.`review_text` AS `review_text`,`online_store_final`.`reviews`.`review_date` AS `review_date` from `online_store_final`.`reviews` where ((`online_store_final`.`reviews`.`review_date` >= '2023-11-01') and (`online_store_final`.`reviews`.`review_date` < '2023-12-01'));

-- -----------------------------------------------------
-- View `online_store_final`.`october23_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_final`.`october23_reviews`;
USE `online_store_final`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `online_store_final`.`october23_reviews` AS select `online_store_final`.`reviews`.`review_id` AS `review_id`,`online_store_final`.`reviews`.`user_id` AS `user_id`,`online_store_final`.`reviews`.`product_id` AS `product_id`,`online_store_final`.`reviews`.`rating` AS `rating`,`online_store_final`.`reviews`.`review_text` AS `review_text`,`online_store_final`.`reviews`.`review_date` AS `review_date` from `online_store_final`.`reviews` where ((`online_store_final`.`reviews`.`review_date` >= '2023-10-01') and (`online_store_final`.`reviews`.`review_date` < '2023-11-01'));

-- -----------------------------------------------------
-- View `online_store_final`.`product_avg_rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_final`.`product_avg_rating`;
USE `online_store_final`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `online_store_final`.`product_avg_rating` AS select `online_store_final`.`products`.`product_id` AS `product_id`,`online_store_final`.`products`.`product_name` AS `product_name`,avg(`online_store_final`.`reviews`.`rating`) AS `average_rating` from (`online_store_final`.`products` left join `online_store_final`.`reviews` on((`online_store_final`.`products`.`product_id` = `online_store_final`.`reviews`.`product_id`))) group by `online_store_final`.`products`.`product_id`,`online_store_final`.`products`.`product_name` order by `average_rating` desc;

-- -----------------------------------------------------
-- View `online_store_final`.`reviews_plus_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_final`.`reviews_plus_user`;
USE `online_store_final`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `online_store_final`.`reviews_plus_user` AS select `online_store_final`.`reviews`.`review_id` AS `review_id`,`online_store_final`.`reviews`.`review_date` AS `review_date`,`online_store_final`.`users`.`full_name` AS `reviewer_name`,`online_store_final`.`products`.`product_name` AS `product_name`,`online_store_final`.`reviews`.`rating` AS `rating`,`online_store_final`.`reviews`.`review_text` AS `review_text` from ((`online_store_final`.`reviews` join `online_store_final`.`users` on((`online_store_final`.`reviews`.`user_id` = `online_store_final`.`users`.`user_id`))) join `online_store_final`.`products` on((`online_store_final`.`reviews`.`product_id` = `online_store_final`.`products`.`product_id`))) order by `online_store_final`.`reviews`.`review_date` desc;

-- -----------------------------------------------------
-- View `online_store_final`.`september23_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store_final`.`september23_reviews`;
USE `online_store_final`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `online_store_final`.`september23_reviews` AS select `online_store_final`.`reviews`.`review_id` AS `review_id`,`online_store_final`.`reviews`.`user_id` AS `user_id`,`online_store_final`.`reviews`.`product_id` AS `product_id`,`online_store_final`.`reviews`.`rating` AS `rating`,`online_store_final`.`reviews`.`review_text` AS `review_text`,`online_store_final`.`reviews`.`review_date` AS `review_date` from `online_store_final`.`reviews` where ((`online_store_final`.`reviews`.`review_date` >= '2023-09-01') and (`online_store_final`.`reviews`.`review_date` < '2023-10-01'));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
